app.id=9025.uni-all-server.uni.ytzh
apollo.meta=http://192.168.60.229:8080
apollo.token=d8e0cedd11c27a24cb71f3d627919e6acf130e60
apollo.accesskey.secret=d8e0cedd11c27a24cb71f3d627919e6acf130e60
apollo.bootstrap.enabled = true
apollo.bootstrap.eagerLoad.enabled=false