name: Java CI
on:
  push:
    branches: [ "fix0826" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set-env-java8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: central
        server-username: SERVER_USERNAME
        server-password: SERVER_PASSWORD
#        gpg-private-key: ${{ secrets.GPG_SECRET }}
        gpg-passphrase: GPG_PASSPHRASE
    - name: maven build
      run: mvn -U clean install -D maven.test.skip=true -D maven.javadoc.skip=true -am package
      env:
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
#        GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}